name: Conditional CI with Override Label

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      ciok_found: ${{ steps.search.outputs.ciok_found }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Search for 'CIOK' in txt files
        id: search
        run: |
          if grep -q 'CIOK' *.txt; then
            echo "ciok_found=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "ciok_found=false" >> $GITHUB_OUTPUT
            exit 0
          fi
    continue-on-error: true

  conditional-check:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.outputs.ciok_found == 'false'
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for ci-override label
        id: check
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          if echo "$LABELS" | grep -q "ci-override"; then
            echo "ci-override label exists"
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "ci-override label does not exist"
            echo "result=failure" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  final-result:
    needs: [test, conditional-check]
    runs-on: ubuntu-latest
    if: |
      needs.test.outputs.ciok_found == 'true' ||
      (needs.test.outputs.ciok_found == 'false' && needs.conditional-check.result == 'success')
    steps:
      - name: Mark pipeline as success
        run: echo "CI passed (either CIOK present or ci-override label present)"

  fail-result:
    needs: [test, conditional-check]
    runs-on: ubuntu-latest
    if: |
      needs.test.outputs.ciok_found == 'false' && needs.conditional-check.result == 'failure'
    steps:
      - name: Mark pipeline as failure
        run: |
          echo "CI failed and no ci-override label present"
          exit 1