name: Comment on CI Failure

on:
  workflow_run:
    workflows: [Check CIOK in txt files]
    types:
      - completed

jobs:
  comment-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Find related pull request
        id: find_pr
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.repo.owner + ':' + github.event.workflow_run.head_branch,
              state: 'open'
            });
            if (prs.data.length > 0) {
              core.setOutput('pr_number', prs.data[0].number);
            }
      - name: Comment on PR
        if: steps.find_pr.outputs.pr_number != ''
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: steps.find_pr.outputs.pr_number,
              body: "CI failed. レビュアーが『OK』と返信すればマージ可能です。"
            });